name: Build SawU PWA for Microsoft Store

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Build PWA package for Microsoft Store
        uses: microsoft/pwa-studio-action@v1
        with:
          url: https://app.sawu.pt
          platform: windows
          packageId: pt.sawu.app
          publisher: CN=d6367a04-4200-4bfe-a197-5fff442f0522
          publisherDisplayName: SawU
